"""P7: the reachability witness, generated from the model and checked on the netlist bytes.

    chips/.venv-fg/bin/python chips/props/witness.py            # writes chips/out/fg.witness.json and
                                                                # chips/props/build/fg_witness.v

The witness is check 1 of the judge guide: two states that the chip reaches from reset, and one input word
that the two states answer with different routes. No function of the inputs can do that; a constant even less.

  trace A:  step(0, X1)                         -> state SA
  trace B:  step(0, X1), then 5 x step(., X2)   -> state SB
  then      step(SA, X2) and step(SB, X2) give different shares and a different release.

X1 is "0.01 OKB of tax arrived" and X2 is "nothing arrived, the reserve holds what the first settle left".
Both are exactly the words the kernel would assemble (the kernel model is run to produce them).

The second part is a tour: one input sequence from reset that visits all five modes.
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CHIPS = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(CHIPS, "model"))

import flow_governor as fg  # noqa: E402
import scenarios as sc  # noqa: E402
from flow_governor import km  # noqa: E402

ROUTE_MASK = (1 << 91) - 1                 # T_*, V_*, REL, CEIL: everything the kernel acts on

WITNESS_FLOWS = [10 ** 16] + [0] * 30
TOUR_FLOWS = [0] + [10 ** 15] * 5 + [4 * 10 ** 16] + [0] * 12


def hx(v: int, nbits: int) -> str:
    """TAP-20 byte string of a vector, as 0x-hex (what `step` takes and returns)."""
    return "0x" + v.to_bytes((nbits + 7) // 8, "little").hex()


def route(y: int) -> dict:
    o = km.unpack_output(y)
    return {k: o[k] for k in ("T_BUY", "T_HOLD", "T_ALLOW", "T_RES", "REL", "CEIL", "MODE", "TIER")} | {
        "modeName": fg.MODE_NAMES[o["MODE"]], "flags": fg.flags_str(o["FLAGS"])}


def build() -> dict:
    t = sc.run("witness", WITNESS_FLOWS)
    pair = sc.find_witness(t)
    assert pair is not None, "no witness in the trace"
    ra, rb = pair
    assert ra.x == rb.x and (ra.y & ROUTE_MASK) != (rb.y & ROUTE_MASK)
    inputs = [r.x for r in t.rows[: rb.epoch - 1]]          # the words fed before the second step of the pair
    # replay with the bare chip (no kernel): the witness must be a pure statement about step()
    s = 0
    states = [0]
    for x in inputs:
        s, _ = fg.step(s, x)
        states.append(s)
    sa, sb = states[ra.epoch - 1], states[rb.epoch - 1]
    assert sa == ra.s_before and sb == rb.s_before
    nsa, ya = fg.step(sa, ra.x)
    nsb, yb = fg.step(sb, ra.x)
    assert ya == ra.y and yb == rb.y

    tour = sc.run("tour", TOUR_FLOWS)
    seen = {}
    for i, r in enumerate(tour.rows):
        seen.setdefault(r.o["MODE"], i)
    assert set(seen) == {0, 1, 2, 3, 4}, f"the tour misses a mode: {seen}"
    # IDLE is the reset state itself; in the tour it shows again once the drought is declared with nothing to release
    return {
        "format": "covenant-witness/1",
        "chip": fg.P["name"],
        "claim": "two reachable states answer one input word with different routes",
        "x": hx(ra.x, 96), "xFields": {k: v for k, v in km.unpack_fields(km.INPUT_FIELDS, ra.x).items() if v},
        "reachA": {"inputs": [hx(x, 96) for x in inputs[: ra.epoch - 1]], "state": hx(sa, 64),
                   "stateFields": fg.unpack_state(sa)},
        "reachB": {"inputs": [hx(x, 96) for x in inputs[: rb.epoch - 1]], "state": hx(sb, 64),
                   "stateFields": fg.unpack_state(sb)},
        "outA": {"y": hx(ya, 112), "newState": hx(nsa, 64), "route": route(ya)},
        "outB": {"y": hx(yb, 112), "newState": hx(nsb, 64), "route": route(yb)},
        "differs": sorted(k for k in ("T_BUY", "T_ALLOW", "T_RES", "REL") if route(ya)[k] != route(yb)[k]),
        "tour": {"inputs": [hx(r.x, 96) for r in tour.rows],
                 "modes": [fg.MODE_NAMES[r.o["MODE"]] for r in tour.rows],
                 "firstStepInMode": {fg.MODE_NAMES[m]: i + 1 for m, i in sorted(seen.items())},
                 "finalState": hx(tour.rows[-1].s_after, 64)},
        "cast": [
            "# free read calls on the taped chip; CPU = processor (Circuits) address, ID = circuit id",
            f"cast call $CPU 'step(uint256,bytes,bytes)(bytes,bytes)' $ID {hx(sa, 64)} {hx(ra.x, 96)}",
            f"cast call $CPU 'step(uint256,bytes,bytes)(bytes,bytes)' $ID {hx(sb, 64)} {hx(ra.x, 96)}",
        ],
    }


def verilog(w: dict) -> str:
    """A closed wrapper (no free inputs): chains of fg_tap instances fed with the witness constants."""
    def lit(h: str, nbits: int) -> str:
        return f"{nbits}'h{int.from_bytes(bytes.fromhex(h[2:]), 'little'):x}"

    L = ["// GENERATED by chips/props/witness.py. P7: reachability witness, on the netlist bytes (fg_tap).",
         "module fg_witness(output wire w_reach_a, output wire w_reach_b, output wire w_same_x_different_route,",
         "                  output wire w_out_a, output wire w_out_b, output wire w_tour_modes, output wire w_tour_end);"]
    xs = w["reachB"]["inputs"]
    L.append("  wire [63:0] c0 = 64'd0;")
    for i, x in enumerate(xs):
        L.append(f"  wire [63:0] c{i + 1}; wire [111:0] cy{i + 1};")
        L.append(f"  fg_tap uc{i + 1}(.s(c{i}), .x({lit(x, 96)}), .ns(c{i + 1}), .y(cy{i + 1}));")
    na, nb = len(w["reachA"]["inputs"]), len(xs)
    L.append(f"  assign w_reach_a = (c{na} == {lit(w['reachA']['state'], 64)});")
    L.append(f"  assign w_reach_b = (c{nb} == {lit(w['reachB']['state'], 64)});")
    L.append("  wire [63:0] na, nb; wire [111:0] ya, yb;")
    L.append(f"  fg_tap ua(.s(c{na}), .x({lit(w['x'], 96)}), .ns(na), .y(ya));")
    L.append(f"  fg_tap ub(.s(c{nb}), .x({lit(w['x'], 96)}), .ns(nb), .y(yb));")
    L.append("  assign w_same_x_different_route = (ya[90:0] != yb[90:0]);")
    L.append(f"  assign w_out_a = (ya == {lit(w['outA']['y'], 112)}) & (na == {lit(w['outA']['newState'], 64)});")
    L.append(f"  assign w_out_b = (yb == {lit(w['outB']['y'], 112)}) & (nb == {lit(w['outB']['newState'], 64)});")
    # tour
    L.append("  wire [63:0] t0 = 64'd0;")
    seen = []
    for i, x in enumerate(w["tour"]["inputs"]):
        L.append(f"  wire [63:0] t{i + 1}; wire [111:0] ty{i + 1};")
        L.append(f"  fg_tap ut{i + 1}(.s(t{i}), .x({lit(x, 96)}), .ns(t{i + 1}), .y(ty{i + 1}));")
    terms = []
    for name, step in w["tour"]["firstStepInMode"].items():
        code = fg.MODE_NAMES.index(name)
        terms.append(f"(ty{step}[93:91] == 3'd{code})")
    L.append(f"  assign w_tour_modes = {' & '.join(terms)};")
    L.append(f"  assign w_tour_end = (t{len(w['tour']['inputs'])} == {lit(w['tour']['finalState'], 64)});")
    L.append("endmodule")
    return "\n".join(L) + "\n"


def main() -> int:
    w = build()
    out = os.path.join(CHIPS, "out", "fg.witness.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        json.dump(w, f, indent=1)
        f.write("\n")
    bdir = os.path.join(HERE, "build")
    os.makedirs(bdir, exist_ok=True)
    with open(os.path.join(bdir, "fg_witness.v"), "w", encoding="utf-8") as f:
        f.write(verilog(w))
    a, b = w["outA"]["route"], w["outB"]["route"]
    print("witness input word:", w["x"], w["xFields"])
    print(f"  state A (after {len(w['reachA']['inputs'])} step):  {w['reachA']['state']}  ->  "
          f"{a['modeName']:6s} buy {a['T_BUY']} allow {a['T_ALLOW']} reserve {a['T_RES']} release {a['REL']}")
    print(f"  state B (after {len(w['reachB']['inputs'])} steps): {w['reachB']['state']}  ->  "
          f"{b['modeName']:6s} buy {b['T_BUY']} allow {b['T_ALLOW']} reserve {b['T_RES']} release {b['REL']}")
    print("  tour:", w["tour"]["firstStepInMode"])
    print("wrote", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
