"""TAP-20 bytes -> structural Verilog.

The result is a pure combinational module describing exactly one beat (TAP-20 section 4):

    module <name>(input [S-1:0] s, input [NIN-1:0] x, output [S-1:0] ns, output [NOUT-1:0] y);

with one `assign n<k> = ~(a & b);` per NAND record. Every LATCH becomes one bit of `s` (its output, the value
stored at the previous beat) and one bit of `ns` (the value of its d signal in this beat), so the module is
core(state, inputs) -> (next_state, outputs) and can be compared with the RTL core by a combinational miter.
Ports of width zero are omitted (no `s`/`ns` for a combinational circuit, no `x` when nIn = 0).

Only flat netlists (no REF) are handled.
"""
from __future__ import annotations

from typing import Optional

from .netlist import LATCH, NAND, OP_NAMES, REF, Netlist, check, keccak256


class UnpackError(ValueError):
    pass


def signal_names(nl: Netlist) -> list:
    """Verilog expression for every signal index of a flat netlist."""
    if not nl.is_flat:
        raise UnpackError("netlist contains REF records; only flat netlists can be unpacked")
    names = ["1'b0", "1'b1"] + [f"x[{i}]" for i in range(nl.n_in)]
    k = 0
    for e in nl.elements:
        if e.op == LATCH:
            names.append(f"s[{k}]")
            k += 1
        else:
            names.append(f"n{e.first_out}")
    return names


def to_verilog(netlist, n_in: Optional[int] = None, n_out: Optional[int] = None, module: str = "chip_tap") -> str:
    """Structural Verilog for one beat of a flat TAP-20 netlist."""
    nl = netlist if isinstance(netlist, Netlist) else check(bytes(netlist), n_in, n_out)
    names = signal_names(nl)
    S, NI, NO = nl.n_state, nl.n_in, nl.n_out
    ports = []
    if S:
        ports.append(f"input [{S - 1}:0] s")
    if NI:
        ports.append(f"input [{NI - 1}:0] x")
    if S:
        ports.append(f"output [{S - 1}:0] ns")
    ports.append(f"output [{NO - 1}:0] y")
    out = [
        f"// Generated by tapc unpack. One beat of a TAP-20 netlist as a pure combinational function.",
        f"// bytes {len(nl.data)}  keccak256 0x{keccak256(nl.data).hex()}",
        f"// nIn {NI}  nOut {NO}  nState {S}  nNand {nl.n_nand}  nLatch {nl.n_latch}",
        f"module {module}({', '.join(ports)});",
    ]
    for e in nl.elements:
        if e.op == NAND:
            out.append(f"  wire n{e.first_out}; assign n{e.first_out} = ~({names[e.ins[0]]} & {names[e.ins[1]]});")
    k = 0
    for e in nl.elements:
        if e.op == LATCH:
            out.append(f"  assign ns[{k}] = {names[e.ins[0]]};")
            k += 1
    first_out = nl.n_signals - NO
    for j in range(NO):
        out.append(f"  assign y[{j}] = {names[first_out + j]};")
    out.append("endmodule")
    return "\n".join(out) + "\n"


def listing(data: bytes, n_in: int, n_out: Optional[int] = None) -> str:
    """Human-readable record listing (a disassembly). Works for any decodable netlist, including REF."""
    from .netlist import decode
    els = decode(data, n_in)
    total = 2 + n_in + sum(e.n_out for e in els)
    lines = [f"; {len(data)} bytes, {len(els)} records, signals 0..{total - 1} "
             f"(0 = const 0, 1 = const 1, 2..{1 + n_in} = inputs)"]
    state = 0
    for i, e in enumerate(els):
        tag = ""
        if n_out is not None and e.first_out + e.n_out > total - n_out:
            tag = f"   ; output {max(e.first_out, total - n_out) - (total - n_out)}"
        if e.op == NAND:
            lines.append(f"{i:6d}  @{e.offset:<6d} s{e.first_out:<7d} NAND  {e.ins[0]} {e.ins[1]}{tag}")
        elif e.op == LATCH:
            lines.append(f"{i:6d}  @{e.offset:<6d} s{e.first_out:<7d} LATCH d={e.ins[0]}   ; state bit {state}{tag}")
            state += 1
        elif e.op == REF:
            lines.append(f"{i:6d}  @{e.offset:<6d} s{e.first_out:<7d} REF   0x{e.cpu.hex()} #{e.cid} "
                         f"ins={list(e.ins)} outs={e.n_out}{tag}")
        else:  # pragma: no cover
            lines.append(f"{i:6d}  {OP_NAMES.get(e.op, '?')}")
    return "\n".join(lines) + "\n"
