// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";

import {KernelV2} from "../../src/KernelV2.sol";
import {KernelFactoryV2} from "../../src/KernelFactoryV2.sol";
import {RecordV2} from "../../src/interfaces/IKernelV2.sol";
import {Envelope} from "core/interfaces/IKernelV1.sol";
import {MockToken, MockPair} from "core-test/mocks/MockIgnix.sol";
import {ChipModel, MockImpl, MockBeacon, MockCircuits, MockSealedVM, MockFab} from "core-test/mocks/MockTapeOut.sol";
import {SealedVM} from "evaluator/SealedVM.sol";
import {MockUSDT0, MockVaultV2, MockManagerV2, MockRouterV2} from "../mocks/MockIgnixV2.sol";

/// @notice The differential test: every settle sequence of chips/golden/vectors_v2.json (generated by
///         gen_vectors_v2.py from the Python model world_v2.py + kernel_model_v2.py) replayed on the real
///         KernelV2 and the Solidity test doubles. After every settle the record, the regime totals, the books
///         and nine balances must equal the model's, bit for bit; every settle the model says reverts must revert
///         with the same error. The Flow Governor sequences run the real netlist (chips/out/fg.hex) on the real
///         SealedVM (contracts/evaluator), checked against the chip's Python model (chips/model/flow_governor.py).
///
///         Every revenue payment in the sequences comes from one address unrelated to the team (`payer`).
contract DiffSettlesV2Test is Test {
    uint256 internal constant T0 = 1_791_000_000;
    uint256 internal constant W = 29; // values per expected settle (gen_vectors_v2.EXPECT_WIDTH)
    address internal constant DEAD = 0x000000000000000000000000000000000000dEaD;

    // event kinds (gen_vectors_v2.py)
    uint256 internal constant E_WARP = 0;
    uint256 internal constant E_CURVE_BUY = 1;
    uint256 internal constant E_CURVE_SELL = 2;
    uint256 internal constant E_V2_BUY = 3;
    uint256 internal constant E_V2_SELL = 4;
    uint256 internal constant E_REVENUE = 5;
    uint256 internal constant E_DONATE_VAULT = 6;
    uint256 internal constant E_CLAIM_FOR = 7;
    uint256 internal constant E_GIFT = 8;
    uint256 internal constant E_SETTLE = 9;
    uint256 internal constant E_EVAL_MODE = 10;
    uint256 internal constant E_VAULT_PAUSE = 11;
    uint256 internal constant E_BUY_PAUSE = 12;
    uint256 internal constant E_WITHDRAW = 13;
    uint256 internal constant E_BURN_LOCKED = 14;
    uint256 internal constant E_GRADUATE = 15;
    uint256 internal constant E_SETTLE_REVERT = 16;

    string internal settlesPath;
    bytes internal fgNetlist;

    address internal launcher = makeAddr("launcher");
    address internal payee = makeAddr("allowance payee");
    address internal keeper = makeAddr("keeper");
    address internal payer = makeAddr("x402 buyer (unrelated to the team)");
    address internal whale = makeAddr("whale");
    address internal bob = makeAddr("bob");

    struct World {
        MockUSDT0 usdt;
        MockManagerV2 manager;
        MockRouterV2 router;
        MockCircuits circuits;
        MockSealedVM mockSealed;
        KernelV2 kernel;
        MockToken token;
        MockVaultV2 vault;
        bool fg;
    }

    // totals, for the report
    uint256 public settlesChecked;

    function setUp() public {
        settlesPath = string.concat(vm.projectRoot(), "/../../chips/golden/vectors_v2_settles.jsonl");
        fgNetlist = vm.parseBytes(vm.trim(vm.readFile(string.concat(vm.projectRoot(), "/../../chips/out/fg.hex"))));
    }

    function _doc() internal view returns (string memory) {
        return vm.readFile(string.concat(vm.projectRoot(), "/../../chips/golden/vectors_v2.json"));
    }

    /// The sequences replayed here are the ones vectors_v2.json names, byte for byte.
    function test_settles_file_is_the_one_vectors_v2_names() public view {
        string memory json = _doc();
        assertEq(vm.parseJsonString(json, ".settlesFile"), "vectors_v2_settles.jsonl");
        bytes32 h = sha256(bytes(vm.readFile(settlesPath)));
        assertEq(vm.toString(h), string.concat("0x", vm.parseJsonString(json, ".settlesSha256")));
    }

    function _env(uint256 i) internal view returns (Envelope memory e) {
        e.launcher = launcher;
        e.allowancePayee = payee;
        e.buyEnabled = true;
        if (i == 0) (e.capT, e.capV, e.allowCumBps, e.ceilMax, e.relMax, e.floorRel, e.floorMin) = (48, 0, 1875, 440, 128, 2, 1);
        if (i == 1) (e.capT, e.capV, e.allowCumBps, e.ceilMax, e.relMax, e.floorRel, e.floorMin) = (64, 128, 2500, 1023, 128, 2, 400);
        if (i == 2) (e.capT, e.capV, e.allowCumBps, e.ceilMax, e.relMax, e.floorRel, e.floorMin) = (128, 0, 5000, 1023, 256, 1, 1);
        if (i == 3) (e.capT, e.capV, e.allowCumBps, e.ceilMax, e.relMax, e.floorRel, e.floorMin) = (32, 0, 500, 420, 64, 8, 425);
        if (i == 0) (e.epochLen, e.fallbackEpochs, e.fbAllow) = (900, 16, 8);
        if (i == 1) (e.epochLen, e.fallbackEpochs, e.fbAllow) = (900, 4, 32);
        if (i == 2) (e.epochLen, e.fallbackEpochs, e.fbAllow) = (900, 2, 128);
        if (i == 3) (e.epochLen, e.fallbackEpochs, e.fbAllow) = (600, 3, 0);
    }

    function test_presets_match_the_generator() public view {
        string memory json = _doc();
        uint256 n = 4;
        for (uint256 i = 0; i < n; i++) {
            string memory k = string.concat(".envPresets[", vm.toString(i), "]");
            Envelope memory e = _env(i);
            assertEq(vm.parseJsonUint(json, string.concat(k, ".capT")), e.capT);
            assertEq(vm.parseJsonUint(json, string.concat(k, ".allowCumBps")), e.allowCumBps);
            assertEq(vm.parseJsonUint(json, string.concat(k, ".ceilMax")), e.ceilMax);
            assertEq(vm.parseJsonUint(json, string.concat(k, ".relMax")), e.relMax);
            assertEq(vm.parseJsonUint(json, string.concat(k, ".floorRel")), e.floorRel);
            assertEq(vm.parseJsonUint(json, string.concat(k, ".floorMin")), e.floorMin);
            assertEq(vm.parseJsonUint(json, string.concat(k, ".epochLen")), e.epochLen);
            assertEq(vm.parseJsonUint(json, string.concat(k, ".fallbackEpochs")), e.fallbackEpochs);
            assertEq(vm.parseJsonUint(json, string.concat(k, ".fbAllow")), e.fbAllow);
        }
        assertEq(vm.parseJsonUint(json, ".expectWidth"), W);
    }

    // ------------------------------------------------------------------ the world of one sequence

    // per-sequence deployment, kept in storage to stay inside the stack
    MockFab internal fab_;
    KernelFactoryV2 internal factory_;

    function _world(uint256[] memory head) internal returns (World memory w) {
        vm.warp(T0);
        w.fg = head[0] == 1;
        w.usdt = new MockUSDT0();
        w.manager = new MockManagerV2(address(w.usdt));
        w.router = new MockRouterV2(address(w.manager), address(w.usdt));
        w.circuits = new MockCircuits();
        fab_ = new MockFab(w.circuits);
        address sealedVm;
        if (w.fg) {
            sealedVm = address(new SealedVM());
        } else {
            w.mockSealed = new MockSealedVM();
            sealedVm = address(w.mockSealed);
        }
        _factory(w, sealedVm, head[1]);
        uint256 id = _chip(w, head);
        w.kernel = KernelV2(factory_.create(_env(head[4]), id, bytes32("diff")));
        (address t, address v) =
            w.manager.createToken(launcher, address(w.kernel), uint16(head[2]), uint16(head[2]), 0, 0, head[3]);
        w.token = MockToken(t);
        w.vault = MockVaultV2(v);
        vm.prank(launcher);
        w.circuits.transferFrom(launcher, address(w.kernel), id);
        w.kernel.bind(t);
    }

    function _factory(World memory w, address sealedVm, uint256 shift) internal {
        MockImpl impl = new MockImpl();
        MockBeacon beacon = new MockBeacon(address(impl));
        factory_ = new KernelFactoryV2(
            address(w.manager),
            address(w.router),
            address(w.usdt),
            shift,
            address(w.circuits),
            address(fab_),
            sealedVm,
            address(beacon),
            address(impl),
            address(impl).codehash
        );
    }

    function _chip(World memory w, uint256[] memory head) internal returns (uint256 id) {
        if (w.fg) {
            // the real netlist: the Fab double records its true shape, and TapeOut's double cannot run it, so the
            // sealed evaluator (the real SealedVM) answers every beat, as the model's `sealed_always` says
            vm.prank(launcher);
            id = fab_.tapeoutChip(fgNetlist, 1952);
            (address ptr,,,,,) = fab_.chipInfo(id);
            fab_.forge(id, ptr, keccak256(fgNetlist), 64, 1952);
            w.circuits.rewriteInfo(id, 96, 112, 64, 1952);
            w.circuits.setStepMode(1);
        } else {
            bytes14[] memory words = new bytes14[](head[6]);
            for (uint256 i = 0; i < words.length; i++) {
                words[i] = bytes14(uint112(head[7 + i]));
            }
            vm.prank(launcher);
            id = fab_.tapeoutChip(ChipModel.scriptChip(head[5], words), 2200);
        }
    }

    function _trader(uint256 i) internal pure returns (address) {
        return address(uint160(0x7700 + i));
    }

    // ------------------------------------------------------------------ replay

    function _run(uint256 seq, string memory line) internal {
        uint256[] memory head = vm.parseJsonUintArray(line, ".head");
        uint256[] memory ev = vm.parseJsonUintArray(line, ".events");
        uint256[] memory ex = vm.parseJsonUintArray(line, ".expects");
        assertEq(ex.length, vm.parseJsonUint(line, ".settled") * W, _at(seq, "expectation width"));
        World memory w = _world(head);
        for (uint256 j = 0; j + 3 < ev.length; j += 4) {
            _event(w, ev[j], ev[j + 1], ev[j + 2], ex, seq);
        }
    }

    function _event(World memory w, uint256 kind, uint256 a, uint256 b, uint256[] memory ex, uint256 seq) internal {
        if (kind == E_WARP) {
            vm.warp(block.timestamp + a);
        } else if (kind == E_CURVE_BUY) {
            w.usdt.mint(_trader(a), b);
            vm.startPrank(_trader(a));
            w.usdt.approve(address(w.manager), b);
            w.manager.buy(address(w.token), b, 0);
            vm.stopPrank();
        } else if (kind == E_CURVE_SELL) {
            vm.startPrank(_trader(a));
            w.token.approve(address(w.manager), b);
            w.manager.sell(address(w.token), b, 0);
            vm.stopPrank();
        } else if (kind == E_V2_BUY || kind == E_V2_SELL) {
            bool buy = kind == E_V2_BUY;
            if (buy) w.usdt.mint(_trader(a), b);
            address[] memory p = new address[](2);
            (p[0], p[1]) = buy ? (address(w.usdt), address(w.token)) : (address(w.token), address(w.usdt));
            vm.startPrank(_trader(a));
            if (buy) w.usdt.approve(address(w.router), b);
            else w.token.approve(address(w.router), b);
            w.router.swapExactTokensForTokensSupportingFeeOnTransferTokens(b, 0, p, _trader(a), block.timestamp);
            vm.stopPrank();
        } else if (kind == E_REVENUE) {
            w.usdt.mint(payer, a);
            vm.prank(payer);
            w.usdt.transfer(address(w.kernel), a);
        } else if (kind == E_DONATE_VAULT) {
            w.usdt.mint(payer, a);
            vm.prank(payer);
            w.usdt.transfer(address(w.vault), a);
        } else if (kind == E_CLAIM_FOR) {
            vm.prank(bob);
            w.vault.claimFor(address(w.kernel), a == 0 ? address(w.usdt) : address(w.token));
        } else if (kind == E_GIFT) {
            vm.prank(_trader(a));
            w.token.transfer(address(w.kernel), b);
        } else if (kind == E_SETTLE) {
            vm.prank(keeper);
            w.kernel.settle();
            _check(w, ex, a, seq);
        } else if (kind == E_EVAL_MODE) {
            if (!w.fg) {
                w.circuits.setStepMode(a == 0 ? 0 : 1);
                w.mockSealed.setStepMode(a == 2 ? 1 : 0);
            }
        } else if (kind == E_VAULT_PAUSE) {
            w.vault.setMode(a == 1 ? 3 : 0);
        } else if (kind == E_BUY_PAUSE) {
            w.manager.setPaused(1, a == 1 ? type(uint64).max : 0);
        } else if (kind == E_WITHDRAW) {
            w.kernel.withdrawCredit(payee, address(w.usdt));
        } else if (kind == E_BURN_LOCKED) {
            w.kernel.burnLocked();
        } else if (kind == E_GRADUATE) {
            w.usdt.mint(whale, a);
            vm.startPrank(whale);
            w.usdt.approve(address(w.manager), a);
            w.manager.buy(address(w.token), a, 0);
            vm.stopPrank();
            assertTrue(w.manager.pairOf(address(w.token)) != address(0), "the graduating buy graduated");
        } else if (kind == E_SETTLE_REVERT) {
            uint32 c0 = w.kernel.count();
            vm.prank(keeper);
            (bool ok, bytes memory ret) = address(w.kernel).call(abi.encodeCall(KernelV2.settle, ()));
            assertFalse(ok, _at(seq, "the model says this settle reverts"));
            bytes4 want = a == 1 ? KernelV2.EpochNotElapsed.selector : KernelV2.StepFailed.selector;
            assertEq(bytes4(ret), want, _at(seq, "revert reason"));
            assertEq(w.kernel.count(), c0);
        } else {
            revert("unknown event");
        }
    }

    function _at(uint256 seq, string memory what) internal pure returns (string memory) {
        return string.concat("sequence ", vm.toString(seq), ": ", what);
    }

    function _check(World memory w, uint256[] memory ex, uint256 idx, uint256 seq) internal {
        uint256 o = idx * W;
        KernelV2 k = w.kernel;
        RecordV2 memory r = k.records(k.count());
        string memory at = string.concat("sequence ", vm.toString(seq), " settle ", vm.toString(idx), ": ");
        assertEq(k.count(), ex[o + 0], string.concat(at, "n"));
        assertEq(r.epoch, ex[o + 1], string.concat(at, "epoch"));
        assertEq(r.time, ex[o + 2], string.concat(at, "time"));
        assertEq(r.clampBits, ex[o + 3], string.concat(at, "clampBits"));
        assertEq(r.flags, ex[o + 4], string.concat(at, "flags"));
        assertEq(uint96(r.inputs), ex[o + 5], string.concat(at, "inputs"));
        assertEq(uint112(r.outputs), ex[o + 6], string.concat(at, "outputs"));
        assertEq(uint256(r.stateAfter), ex[o + 7], string.concat(at, "stateAfter"));
        assertEq(r.inflow, ex[o + 8], string.concat(at, "inflow"));
        assertEq(r.reserveBefore, ex[o + 9], string.concat(at, "reserveBefore"));
        assertEq(r.allow, ex[o + 10], string.concat(at, "allow"));
        assertEq(r.buyDecided, ex[o + 11], string.concat(at, "buyDecided"));
        assertEq(r.buyExecuted, ex[o + 12], string.concat(at, "buyExecuted"));
        assertEq(r.tokensOut, ex[o + 13], string.concat(at, "tokensOut"));
        assertEq(r.quoteIn, ex[o + 14], string.concat(at, "quoteIn"));
        (uint128 cum, uint128 paid) = k.cums(k.count());
        assertEq(cum, ex[o + 15], string.concat(at, "cumInflow"));
        assertEq(paid, ex[o + 16], string.concat(at, "allowPaidCum"));
        assertEq(k.reserve(), ex[o + 17], string.concat(at, "reserve"));
        assertEq(k.totalCredits(address(w.usdt)), ex[o + 18], string.concat(at, "totalCredits(USDT0)"));
        assertEq(k.totalCredits(address(w.token)), ex[o + 19], string.concat(at, "totalCredits(token)"));
        assertEq(k.lockedTokens(), ex[o + 20], string.concat(at, "locked"));
        assertEq(k.burnedTokens(), ex[o + 21], string.concat(at, "burned"));
        assertEq(w.usdt.balanceOf(address(k)), ex[o + 22], string.concat(at, "kernel USDT0"));
        assertEq(w.token.balanceOf(address(k)), ex[o + 23], string.concat(at, "kernel tokens"));
        assertEq(w.token.balanceOf(DEAD), ex[o + 24], string.concat(at, "0xdEaD tokens"));
        assertEq(w.usdt.balanceOf(address(w.vault)), ex[o + 25], string.concat(at, "vault USDT0"));
        assertEq(w.token.balanceOf(address(w.vault)), ex[o + 26], string.concat(at, "vault tokens"));
        assertEq(k.graduated() ? 1 : 0, ex[o + 27], string.concat(at, "graduated"));
        assertEq(k.creditOf(payee, address(w.usdt)), ex[o + 28], string.concat(at, "payee credit"));
        // nothing approved is left behind
        assertEq(w.usdt.allowance(address(k), address(w.manager)), 0, string.concat(at, "Manager allowance"));
        assertEq(w.usdt.allowance(address(k), address(w.router)), 0, string.concat(at, "router allowance"));
        settlesChecked++;
    }

    function _runBatch(uint256 part, uint256 parts) internal {
        uint256 n = vm.parseJsonUint(_doc(), ".settleSequences");
        uint256 from = (n * part) / parts;
        uint256 to = (n * (part + 1)) / parts;
        for (uint256 i = 0; i < to; i++) {
            string memory line = vm.readLine(settlesPath); // one sequence per line
            if (i >= from) _run(i, line);
        }
        emit log_named_uint("sequences replayed", to - from);
        emit log_named_uint("settles compared", settlesChecked);
    }

    // eight batches, so that forge runs them in parallel
    function test_diff_settles_batch_0() public {
        _runBatch(0, 8);
    }

    function test_diff_settles_batch_1() public {
        _runBatch(1, 8);
    }

    function test_diff_settles_batch_2() public {
        _runBatch(2, 8);
    }

    function test_diff_settles_batch_3() public {
        _runBatch(3, 8);
    }

    function test_diff_settles_batch_4() public {
        _runBatch(4, 8);
    }

    function test_diff_settles_batch_5() public {
        _runBatch(5, 8);
    }

    function test_diff_settles_batch_6() public {
        _runBatch(6, 8);
    }

    function test_diff_settles_batch_7() public {
        _runBatch(7, 8);
    }
}
